-- 行程订单表
CREATE TABLE `tour_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `tour_id` BIGINT NOT NULL COMMENT '行程ID',
  `tour_name` VARCHAR(255) NOT NULL COMMENT '行程名称',
  `tour_code` VARCHAR(50) NOT NULL COMMENT '行程编号',
  `package_id` BIGINT NOT NULL COMMENT '套餐ID',
  `package_name` VARCHAR(100) NOT NULL COMMENT '套餐名称',
  `batch_package_id` BIGINT DEFAULT NULL COMMENT '批次套餐ID',
  `batch_package_name` VARCHAR(100) DEFAULT '标准' COMMENT '批次套餐名称',
  `departure_date` DATE NOT NULL COMMENT '出发日期',
  `adult_count` INT NOT NULL DEFAULT 1 COMMENT '成人数量',
  `child_count` INT DEFAULT 0 COMMENT '儿童数量',
  `adult_unit_price` DECIMAL(10,2) NOT NULL COMMENT '成人单价',
  `child_unit_price` DECIMAL(10,2) DEFAULT 0.00 COMMENT '儿童单价',
  `tour_amount` DECIMAL(10,2) NOT NULL COMMENT '行程费用（不含酒店）',
  `hotel_id` BIGINT DEFAULT NULL COMMENT '酒店ID',
  `hotel_name` VARCHAR(255) DEFAULT NULL COMMENT '酒店名称',
  `hotel_days` INT DEFAULT NULL COMMENT '酒店住宿天数',
  `hotel_price_per_night` DECIMAL(10,2) DEFAULT NULL COMMENT '酒店每晚价格',
  `hotel_amount` DECIMAL(10,2) DEFAULT 0.00 COMMENT '酒店总费用',
  `total_amount` DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
  `contact_name` VARCHAR(50) DEFAULT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) DEFAULT NULL COMMENT '联系人电话',
  `status` INT NOT NULL DEFAULT 0 COMMENT '订单状态: 0-待支付, 1-已支付, 2-已取消, 3-已退款, 4-已完成',
  `payment_method` VARCHAR(50) DEFAULT NULL COMMENT '支付方式',
  `payment_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `remark` TEXT DEFAULT NULL COMMENT '备注',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_tour_id` (`tour_id`),
  KEY `idx_departure_date` (`departure_date`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='行程订单表';
